server:
  port: 8050
spring:
  application:
    name: gateway-zull
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
zuul:
  ignoredServices: '*'
  routes:
    app-a:
      path: /user/**
      serviceId: consumer-user
    app-sidecar:
      path: /sidecar/**
      serviceId: sidecar